dist: xenial
os:
    # - linux
    # - osx
    - windows

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
    matrix:
        - BLENDER_VERSION="2.80"
        - BLENDER_VERSION="2.81a"
        - BLENDER_VERSION="2.82"
        - BLENDER_VERSION="2.83"

language: python
python:
    - "3.7"

cache:
    directories:
        - ${BLENDER_CACHE}

addons:
    apt:
        packages:
            - blender

before_install:
    - python scripts/travis/before_install.py
install:
    - python -m pip install -r requirements.txt
    - python --version
    - python scripts/travis/get_blender.py --version=${BLENDER_VERSION}

script:
    - ./external/blender-${BLENDER_VERSION}/blender.exe --version
    - python scripts/run_blender.py --version=${BLENDER_VERSION}
    - ls
    # - bash <(curl -s https://codecov.io/bash)

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
