dist: xenial

os:
    - linux
#    - osx 
#    - windows

env:
    global:
        - BLENDER_CACHE=$HOME/.cache/blender
        - VENV_CACHE=$HOME/.cache/venv
        - PYTHON_REV=3.7.5
    matrix:
        - BLENDER_VERSION="2.78c"
        - BLENDER_VERSION="2.79b"
        - BLENDER_VERSION="2.80"
        - BLENDER_VERSION="2.81a"
        - BLENDER_VERSION="2.82"
        - BLENDER_VERSION="2.83"

language: bash

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - ${BLENDER_CACHE}
        - ${VENV_CACHE}

addons:
    apt:
        packages:
            - blender

before_install:
    - mkdir -p ${BLENDER_CACHE}
    - ls ${BLENDER_CACHE}
    - mkdir -p ${VENV_CACHE}
    - source ${TRAVIS_BUILD_DIR}/scripts/get_python.sh
    - pip install -r ${TRAVIS_BUILD_DIR}/scripts/requirements.txt --upgrade
    - yolk -l

install:
    - cd $TRAVIS_BUILD_DIR
    - python --version
    - python ${TRAVIS_BUILD_DIR}/scripts/get_blender.py ${BLENDER_VERSION}

script:
    - cd ${TRAVIS_BUILD_DIR}
    #- ../blender-${BLENDER_VERSION}/blender --version
    - python ${TRAVIS_BUILD_DIR}/scripts/run_blender.py ${BLENDER_VERSION}
    - ls
    - bash <(curl -s https://codecov.io/bash)

#after_success:
#    - codecov -f tests_output/coverage.xml

notifications:
    email:
        on_success: change
        on_failure: always
