name: blender-fake-addon

on: 
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        blender-version: ["2.78c", "2.79b", "2.80", "2.81a", "2.82", "2.83"]
        os: [ubuntu-latest, windows-latest]
        #blender-version: ["2.80"]
        #os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python --version
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
        yolk -l

    - name: Set up System Blender
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt update
        sudo apt install -f -y blender

    - name: Download Blender ${{ matrix.blender-version }}
      run: |
        python scripts/get_blender.py ${{ matrix.blender-version }}
    - name: Test Blender ${{ matrix.blender-version }} with pytest
      run: |
        python scripts/run_blender.py ${{ matrix.blender-version }}
